# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monad_hindex
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: WETHTokenMintERC20Token
    address:
    - 0xB5a30b0FDc5EA94A52fDc42e3E9760Cb8449Fb37
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: DAKTokenMintERC20Token
    address:
    - 0x0F0BDEbF0F83cD1EE3974779Bcb7315f9808c714
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: YAKITokenMintERC20Token
    address:
    - 0xfe140e1dCe99Be9F4F15d657CD9b7BF622270C50
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: CHOGTokenMintERC20Token
    address:
    - 0xE0590015A873bF326bd645c3E1266d4db41C4E6B
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
