# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monad_hindex
networks:
- id: 1
  start_block: 0
  contracts:
  - name: TokenMintERC20Token
    address:
    - 0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
- id: 8453
  start_block: 0
  contracts:
  - name: FiatTokenProxy
    address:
    - 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
    handler: src/EventHandlers.ts
    events:
    - event: AdminChanged(address previousAdmin, address newAdmin)
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: AuthorizationCanceled(address indexed authorizer, bytes32 indexed nonce)
    - event: AuthorizationUsed(address indexed authorizer, bytes32 indexed nonce)
    - event: Blacklisted(address indexed _account)
    - event: BlacklisterChanged(address indexed newBlacklister)
    - event: Burn(address indexed burner, uint256 amount)
    - event: MasterMinterChanged(address indexed newMasterMinter)
    - event: Mint(address indexed minter, address indexed to, uint256 amount)
    - event: MinterConfigured(address indexed minter, uint256 minterAllowedAmount)
    - event: MinterRemoved(address indexed oldMinter)
    - event: OwnershipTransferred(address previousOwner, address newOwner)
    - event: Pause()
    - event: PauserChanged(address indexed newAddress)
    - event: RescuerChanged(address indexed newRescuer)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: UnBlacklisted(address indexed _account)
    - event: Unpause()
    - event: Upgraded(address implementation)
